# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       attr
Summary:    Utilities for managing filesystem extended attributes
Version:    2.4.46
Release:    1
Group:      System/Base
License:    GPLv2+
URL:        http://savannah.nongnu.org/projects/attr
Source0:    http://download.savannah.gnu.org/releases/attr/attr-%{version}.src.tar.gz
Source100:  attr.yaml
Patch0:     attr-2.4.32-build.patch
Patch1:     attr-2.4.44-warnings.patch
Patch2:     attr-2.4.44-bz660619.patch
Patch3:     attr-2.4.44-bz660613.patch
Patch4:     attr-2.4.44-bz669095.patch
BuildRequires:  gettext
BuildRequires:  libtool >= 1.5


%description
A set of tools for manipulating extended attributes on filesystem
objects, in particular getfattr(1) and setfattr(1).
An attr(1) command is also provided which is largely compatible
with the SGI IRIX tool of the same name.



%package -n libattr-devel
Summary:    Extended attribute static libraries and headers
License:    LGPLv2+
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   libattr = %{version}

%description -n libattr-devel
This package contains the libraries and header files needed to
develop programs which make use of extended attributes.
For Linux programs, the documented system call API is the
recommended interface, but an SGI IRIX compatibility interface
is also provided.

Currently only ext2, ext3 and XFS support extended attributes.
The SGI IRIX compatibility API built above the Linux system calls is
used by programs such as xfsdump(8), xfsrestore(8) and xfs_fsr(8).

You should install libattr-devel if you want to develop programs
which make use of extended attributes.  If you install libattr-devel,
you'll also want to install attr.


%package -n libattr
Summary:    Dynamic library for extended attribute support
License:    LGPLv2+
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n libattr
This package contains the libattr.so dynamic library which contains
the extended attribute system calls and library functions.



%prep
%setup -q -n %{name}-%{version}

# attr-2.4.32-build.patch
%patch0 -p1
# attr-2.4.44-warnings.patch
%patch1 -p1
# attr-2.4.44-bz660619.patch
%patch2 -p1
# attr-2.4.44-bz660613.patch
%patch3 -p1
# attr-2.4.44-bz669095.patch
%patch4 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --libdir=/%{_lib} \
    --libexecdir=%{_libdir}


# >> build post
make %{?_smp_mflags}  LIBTOOL="libtool --tag=CC"
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
make install-dev DESTDIR=%{buildroot}
make install-lib DESTDIR=%{buildroot}

# get rid of libattr.a and libattr.la
rm -f %{buildroot}/%{_lib}/libattr.a
rm -f %{buildroot}/%{_lib}/libattr.la
rm -f %{buildroot}%{_libdir}/libattr.a
rm -f %{buildroot}%{_libdir}/libattr.la

# fix links to shared libs and permissions
rm -f %{buildroot}/%{_libdir}/libattr.so
ln -sf ../../%{_lib}/libattr.so %{buildroot}/%{_libdir}/libattr.so
chmod 0755 %{buildroot}/%{_lib}/libattr.so.*.*.*

rm -rf %{buildroot}%{_docdir}

%find_lang %{name}
%docs_package
%lang_package
# << install post










%post -n libattr -p /sbin/ldconfig

%postun -n libattr -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%doc doc/COPYING
%{_bindir}/attr
%{_bindir}/getfattr
%{_bindir}/setfattr
# << files


%files -n libattr-devel
%defattr(-,root,root,-)
# >> files libattr-devel
/%{_lib}/libattr.so
%{_includedir}/attr
%{_libdir}/libattr.*
# << files libattr-devel

%files -n libattr
%defattr(-,root,root,-)
# >> files libattr
/%{_lib}/libattr.so.*
# << files libattr

